blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@terros-inc/*'
packageManagerStrictVersion: true
trustPolicy: no-downgrade
updateNotifier: false
verifyDepsBeforeRun: warn
