allowBuilds:
  esbuild: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@terros-inc/*'
trustPolicy: no-downgrade
updateNotifier: false
pmOnFail: error
verifyDepsBeforeRun: warn
